title: Find-a-gig API Documentation
description: A GitHub Pages site built with Jekyll
baseurl: "/find-a-gig" # Leave blank for root-level deployment
url: "https://hood-casu.github.io"
theme: minima # Default GitHub Pages theme
markdown: kramdown
permalink: pretty
header_pages:
  -index.md
  -api-reference.md
  -tutorials.md
author:
  -name: Caitlin Hood
minima:
  social_links:
    - { platform: linkedin, user_url: "www.linkedin.com/in/caitlin-hood-a115a35b"}

  
